image: node:8-alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apk add --no-cache curl file grep libidn make zip
    - HOSTNAME= make release
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - cp -r dist/ public/
  artifacts:
    paths:
      - public/
  only:
    - master
