image: node:8-alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apk add --no-cache curl file gawk grep libidn make sed zip
    - make build stats index
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - npm install firebase-tools
    - PATH="node_modules/firebase-tools/bin:${PATH}"
    - firebase use --token "${FIREBASE_TOKEN}" "${FIREBASE_PROJECT}"
    - firebase deploy --token "${FIREBASE_TOKEN}" --message "Pipeline ${CI_PIPELINE_ID}, job ${CI_JOB_ID}"
  cache:
    paths:
      - node_modules/
  only:
    - master
